### ISSUE TITLE
Request: Make the package installable with pip

### ISSUE THREAD

**Issue by diskxo** [tombulled/python-youtube-music#10]
Hi everyone, I'm trying to install this package in my HomeAssistant server with AppDaemon 4, but I need to install this with a "pip install" method, because the only method I have to install ytm package is this: 
![image](https://user-images.githubusercontent.com/64780086/109423196-dfd65b80-79de-11eb-9052-7bfb53c69908.png) :')

there is no alternative method to pip install setup.py?
Thanks

**Comment by tombulled** [comment]
Hi @diskxo,

You are actually able to install the package using pip:
```console
$ python3 -m pip install git+https://github.com/tombulled/python-youtube-music
```

However, I assume you mean installing it directly from PyPi. As this package is no longer actively maintained (I have another revised one in the works though!), I have no intention of uploading this package to PyPi unfortunately.

The improved version I mentioned should hopefully be publicly available in a matter of weeks, with the intention to upload this version to PyPi.

**Comment by diskxo** [comment]
Thanks a lot :D
