### ISSUE TITLE
:bug: "No data to parse" while getting a song object

### ISSUE THREAD

**Issue by CyberedCake** [tombulled/python-youtube-music#23]
A "No Data To Parse" error occurs whenever I try to create a song object, even when using the same ID as in the example in the [README](https://github.com/tombulled/python-youtube-music#method---song:~:text=song(%27-,pPt_FZ9m2bM,-%27)%0A%3E%3E). I tried some other songs, including Welcome to the Internet by Bo Burnham, and it still didn't work.

![image](https://user-images.githubusercontent.com/61170080/208116836-088abadd-5e69-4492-b2f3-480d041b8032.png)

After which I tried, `api.search_songs("Welcome to the Internet")`, where the results have the ID included in them. After also attempting to create a song using that ID, it still gave me the "No data to parse exception".

✔️ I am using the latest version
✔️ I have installed all dependencies, optional and required
✔️ I have followed instructions to the best of my ability
ℹ️ I am using Windows 10 Enterprise 22H2. (high school laptop, so not very good specs in general)

Lemme know if this is an error on my side or if it's not replicable.

**Comment by tombulled** [comment]
Hi @CyberedCake, thanks for raising this issue. YouTube is always changing the data that the innertube API returns slightly, therefore that is likely what's happened here. It's very unlikely that this is at all an error on your side - I'll see if I'm able to reproduce the issue

**Comment by tombulled** [comment]
Interestingly I'm not even able to instantiate a client:
```python
import ytm

api = ytm.YouTubeMusic()
```
```console
$ python3  app.py
MethodError: Page has no configuration data
```

**Comment by tombulled** [comment]
So the `.song` method uses the `get_video_info` endpoint under the hood, e.g. https://www.youtube.com/get_video_info?video_id=k1BneeJTDcU however this appears to be returning an empty response which is strange. I wonder whether YouTube as deprecated this endpoint :confused:

**Comment by tombulled** [comment]
It's returning a 410 Gone which is ominous and might confirm the suspicion that YouTube has remove it:
```console
$ http "https://www.youtube.com/get_video_info?video_id=k1BneeJTDcU" 
HTTP/1.1 410 Gone
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private, max-age=86400
Content-Length: 0
Content-Type: text/html; charset=utf-8
Cross-Origin-Opener-Policy-Report-Only: same-origin; report-to="youtube_main"
Date: Wed, 04 Jan 2023 22:31:29 GMT
Expires: Wed, 04 Jan 2023 22:31:29 GMT
P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en-GB for more info."
Permissions-Policy: ch-ua-arch=*, ch-ua-bitness=*, ch-ua-full-version=*, ch-ua-full-version-list=*, ch-ua-model=*, ch-ua-wow64=*, ch-ua-platform=*, ch-ua-platform-version=*
Report-To: {"group":"youtube_main","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/youtube_main"}]}
Server: ESF
Set-Cookie: YSC=0MjtisSPpOY; Domain=.youtube.com; Path=/; Secure; HttpOnly; SameSite=none
Set-Cookie: VISITOR_INFO1_LIVE=cQnegyRGuTE; Domain=.youtube.com; Expires=Mon, 03-Jul-2023 22:31:29 GMT; Path=/; Secure; HttpOnly; SameSite=none
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 0
```

**Comment by tombulled** [comment]
I'm going to close this issue as there's little I'm able to do for this library, beyond deprecating the `.song` method
