### ISSUE TITLE
Python doesn't find the package

### ISSUE THREAD

**Issue by diskxo** [tombulled/python-youtube-music#9]
I tryed to insert this code and run it, but, after the installation of the package, python doesn't find it.
![image](https://user-images.githubusercontent.com/64780086/108604716-e72eb100-73af-11eb-9f11-171151aa1899.png)
How can I resolve this error?
![image](https://user-images.githubusercontent.com/64780086/108604733-fd3c7180-73af-11eb-8d09-23d92236704b.png)

**Comment by tombulled** [comment]
Your file is named `ytm.py` which Python will recognise as a module named `ytm`, which is also the name of the module you're trying to import. To resolve this issue, rename your `ytm.py` file to something else (e.g. `app.py`)

**Comment by diskxo** [comment]
> Your file is named `ytm.py` which Python will recognise as a module named `ytm`, which is also the name of the module you're trying to import. To resolve this issue, rename your `ytm.py` file to something else (e.g. `app.py`)

If I rename the file, it gives me this error:

![image](https://user-images.githubusercontent.com/64780086/108604956-3cb78d80-73b1-11eb-8f27-d0439e23b283.png)

**Comment by tombulled** [comment]
In `app.py` you use the line:
```python
ytm = ytm.YouTubeMusic()
```
This will overwrite the reference to the `ytm` module, which is then used again in the line:
```python
return song_url(ytm.YouTubeMusic().search_songs(query)['items'][0]['id'])
```
To fix this, your code should look something like this:
```python
import ytm

youtubemusic = ytm.YouTubeMusic()

def song_url(song_id: str) -> str:
    return ytm.utils.url_ytm('watch', params = {'v': song_id})

def search(query: str) -> str:
    return song_url(youtubemusic.search_songs(query)['items'][0]['id'])

print(search('liztomania'))
```
Hope this helps!

**Comment by diskxo** [comment]
![image](https://user-images.githubusercontent.com/64780086/108609807-cdea2c80-73d0-11eb-807d-e9bb5218d544.png)

Thank you very much!! I didn't think the name of the variable would give problems ... XD
